language: 'ja'
early_access: false
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    drafts: false
    base_branches:
      - 'feature/*'
chat:
  auto_reply: true
